export const menuList = [
	{
		id: 1,
		title: "Senin Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 2,
		title: "Senin Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 3,
		title: "Senin Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 4,
		title: "Senin Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 5,
		title: "Senin Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 6,
		title: "Senin Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 7,
		title: "Senin Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 8,
		title: "Senin Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 9,
		title: "Senin Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "senin",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 10,
		title: "Selasa Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 11,
		title: "Selasa Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 12,
		title: "Selasa Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 13,
		title: "Selasa Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 14,
		title: "Selasa Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 15,
		title: "Selasa Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 16,
		title: "Selasa Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 17,
		title: "Selasa Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 18,
		title: "Selasa Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "selasa",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 19,
		title: "Rabu Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 20,
		title: "Rabu Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 21,
		title: "Rabu Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 22,
		title: "Rabu Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 23,
		title: "Rabu Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 24,
		title: "Rabu Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 25,
		title: "Rabu Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 26,
		title: "Rabu Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 27,
		title: "Rabu Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "rabu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 28,
		title: "Kamis Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 29,
		title: "Kamis Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 30,
		title: "Kamis Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 31,
		title: "Kamis Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 32,
		title: "Kamis Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 33,
		title: "Kamis Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 34,
		title: "Kamis Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 35,
		title: "Kamis Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 36,
		title: "Kamis Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "kamis",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 37,
		title: "Jumat Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 38,
		title: "Jumat Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 39,
		title: "Jumat Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 40,
		title: "Jumat Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 41,
		title: "Jumat Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 42,
		title: "Jumat Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 43,
		title: "Jumat Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 44,
		title: "Jumat Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 45,
		title: "Jumat Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "jumat",

		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 46,
		title: "Sabtu Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 47,
		title: "Sabtu Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 48,
		title: "Sabtu Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 49,
		title: "Sabtu Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 50,
		title: "Sabtu Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 51,
		title: "Sabtu Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 52,
		title: "Sabtu Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 53,
		title: "Sabtu Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 54,
		title: "Sabtu Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "sabtu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 55,
		title: "Minggu Sarapan 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu4",
		imageAlt: "menu4",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 56,
		title: "Minggu Sarapan 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "sarapan",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "20g",
			protein: "40g",
			karbohidrat: "18g",
		},
		kalori: "300",
	},
	{
		id: 57,
		title: "Minggu Sarapan 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "sarapan",
		harga: "20.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 58,
		title: "Minggu Makan Siang 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 59,
		title: "Minggu Makan Siang 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 60,
		title: "Minggu Makan Siang 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "makansiang",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 61,
		title: "Minggu Makan Malam 1",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu1",
		imageAlt: "menu1",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 62,
		title: "Minggu Makan Malam 2",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu2",
		imageAlt: "menu2",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
	{
		id: 63,
		title: "Minggu Makan Malam 3",
		deskripsi: "deskripsi singkat makanan ini",
		bahan: ["bahan 1", "bahan 2", "bahan 3"],
		hari: "minggu",
		waktu: "makanmalam",
		harga: "25.000",
		imageName: "menu3",
		imageAlt: "menu3",
		nutrisi: {
			lemak: "10g",
			protein: "10g",
			karbohidrat: "10g",
		},
		kalori: "300",
	},
];
