export const data = [
	{
		id: 0,
		title: "Memilih Jenis Buah untuk Penyajian Salad Buah yang Sehat",
		date: "9 Februari 2022",
		article: [
			"Halodoc, Jakarta – Musim panas adalah waktu yang tepat untuk memanfaatkan semua pilihan buah segar yang ada. Kamu pun bisa membuat salad buah yang penuh cita rasa. Apalagi kamu juga sangat beruntung tinggal di Indonesia karena berbagai jenis buah dapat ditemukan dengan mudah sepanjang tahun.",
			"Membuat salad buah yang ringan dan sehat adalah salah satu cara termudah untuk mengolah buah. Cara membuatnya pun mudah dan tidak membutuhkan banyak bahan tambahan. Kamu bisa mendapatkan berbagai rasa darinya, mulai dari manis, sedikit asam dan pastinya menyegarkan.",
			"Kamu harus memastikan untuk memilih buah yang tinggi nutrisi untuk disajikan dalam salad buah. Nah, kamu bisa menyajikan buah-buahan berikut dalam menu salad buah untuk mendapatkan rasa yang nikmat dan manfaat dan nutrisi darinya: ",
			"Apel Nanas Alpukat Anggur Dilema Stroberi Mangga Jeruk Pepaya",
		],
		imageName: "kateringsehat.jpg",
		imageAlt: "Buah segar yang sehat",
	},
	{
		id: 1,
		title: "Makanan yang Sehat dan Enak",
		date: "5 Februari 2022",
		article: [
			"Makanan yang sehat dan enak adalah salah satu hal yang harus kamu lakukan untuk menjaga kesehatan dan kesehatan tubuh. Namun, kamu bisa mengolah makanan dengan cara yang mudah dan mudah. Kamu bisa memilih makanan yang sehat dan enak dengan cara yang mudah dan mudah.",
			"Kamu bisa memilih makanan yang sehat dan enak dengan cara yang mudah dan mudah. Kamu bisa memilih makanan yang sehat dan enak dengan cara yang mudah dan mudah.",
		],
		imageName: "aturmenu.jpg",
		imageAlt: "Makanan Sehat dan Enak",
	},
	{
		id: 2,
		title: "8 Makanan Enak Ini Ternyata Berkhasiat Untuk Kesehatan Mata",
		date: "31 Januari 2022",
		article: [
			"Jakarta(detik.com) - Tidak hanya wortel, ternyata banyak makanan enak yang juga bermanfaat untuk kesehatan mata. Ada ubi, telur hingga pepaya semuanya juga dipercaya berkhasiat untuk jernihkan penglihatan.",
			"Selama ini kesehatan mata selalu dikaitkan dengan wortel. Ternyata tak hanya sayuran berbentuk kerucut berwarna oranye itu saja, ada juga beberapa makanan enak lainnya yang dipercaya berkhasiat untuk mata.",
			"Semua makanan yang mengandung vitamin A dianggap memiliki kunci utama untuk menjaga kesehatan mata. Bahkan beberapa jenis makanan ini dianggap memiliki kandungan nutrisi yang lebih lengkap daripada wortel.",
			"Ada kandungan vitamin C, vitamin E, Zinc, selenium dan omega-3 yang juga diperlukan oleh tubuh terdapat pada beberapa makanan lain selain wortel. Semua makanan enak ini bisa dikonsumsi sebagai camilan maupun dicampurkan ke dalam menu utama makanan sehari-hari.",
			"1. Ubi",
			"2. Telur",
			"3. Bayam dan Sayuran Hijau",
			"4. Tiram",
			"5. Kacang Almond",
			"6. Pepaya",
			"7. Ikan Berminyak",
			"8. Kacang Kacangan",
		],
		imageName: "salad.jpg",
		imageAlt: "salad",
	},
	{
		id: 3,
		title: "Chef Eddrian Tjhia Ungkap Menu Sehat yang Bakal Tren Tahun 2022",
		date: "09 Januari 2022",
		article: [
			"Jakarta - Chef Eddrian Tjhia memprediksi bahwa makanan sehat masih diminati di tahun 2022. Menu makanan sehat apa saja yang akan jadi tren?",
			"Chef spesialis makanan Bangka dan makanan sehat, Eddrian Tjhia mengatakan bahwa pandemi COVID-19 membuat banyak orang semakin sadar betapa pentingnya menjalani pola makan sehat. Karenanya, makanan sehat diprediksi masih akan terus diminati banyak orang. Menurutnya, menjalani pola makan sehat bisa menjadi resolusi di tahun baru.",
			`"Karena kedepannya kita gak tahu pandemi kapan berakhir. Kita tetap fokus untuk menjaga diri masing-masing. Pola makan yang sehat dan pola hidup yang sehat dengan olahraga yang cukup," ujar Chef Eddrian Tjhia kepada detikcom (08/01/22).`,
			"Menjalani pola makan sehat bisa dimulai dengan menghindari karbohidrat, lemak dan makanan manis secara berlebih. Chef Eddrian menyarankan untuk berfokus pada makanan bergizi.",
			`"Contoh setiap pagi minum madu, minum air putih yang banyak. Sarapan pakai oatmeal, susu, telur. Kalau siang makan daging. Cara makan daging kan gak harus digoreng," tuturnya.`,
			"Lebih lanjut, Chef yang baru saja meluncurkan buku 'Fresh & Super Simple Cooking' ini juga menekankan tentang pentingnya pola makan seimbang, yakni dengan memperhatikan asupan nutrisi.",
			`"Jadi banyak-banyak makan sayuran. Asupan nutrisi itu penting buat diperhatikan. Mulai dari vitaminnya, protein sampai serat," ujar Chef Eddrian Tjhia.`,
			"Lantas menu sehat seperti apa yang diprediksi akan menjadi tren di tahun 2022? Chef Eddrian Tjhia mengatakan bahwa salad masih akan diminati banyak orang.",
			`Salad masih, karena dominan sehat. Salad kan banyak sekali, ada salad sayur pada salad buah. Salad buah bisa pakai buah pir dan kismis. Nanti dressingnya bisa pakai minyak bawang putih, ditambah kacang-kacangan," kata Chef Eddrian.`,
			"Selain salad, smoothie buah dan sayuran pun tak kalah jadi favorit. Menurutnya smoothie dapat mudah dibuat di rumah, karena menggunakan bahan-bahan yang sederhana.",
			"Menurut Chef Eddrian Tjhia, pentingnya menjaga pola makan sehat ini bukan hanya untuk menjaga imunitas di tengah pandemi COVID-19, tetapi juga untuk menjaga tubuh dari segala penyakit.",
			`"Pandemi gak tau kapan harus berakhir, harus lebih pinter menjaga kesehatan tubuh kita, supaya kita tetap sehat. Bukan karena virus corona aja, tapi dari penyakit lainnya juga," tutupnya.`,
		],
		imageName: "oatmeal.jpg",
		imageAlt: "oatmeal",
	},
	{
		id: 4,
		title: "Tips makanan sehat bagi orang yang sibuk",
		date: "7 Oktober 2021",
		article: [
			"sultantv.co - Mengonsumsi makanan sehat merupakan salah satu hal yang sering dilakukan seseorang untuk terus menjaga kesehatan di dalam tubuhnya. Bukan hanya itu saja, makanan sehat juga dapat memberikan suasana hati yang lebih baik untuk Anda.",
			"Prinsip empat sehat lima sempurna merupakan salah satu semoga yang pasti ada di dalam kepala Anda. Sedangkan ini mungkin sudah Anda dengar sejak anak masih kecil. Namun tahukah Anda mengapa slogan tersebut kini sudah tidak digunakan lagi? Pada tahun 2014 lalu jargon tersebut telah diganti menjadi pedoman gizi seimbang. Itulah penyebab mengapa kini slogan lama tersebut tidak digunakan kembali.",
			"Beberapa alasan mengapa semoga empat sehat lima sempurna tidak lagi digunakan adalah misalnya jika hanya memakan makanan saya saja itu tidaklah cukup untuk tubuh Anda. Selain itu susu bukanlah minuman wajib jadi pelangkap makanan Anda. Kemudian tidak ada ketentuan versi yang ditetapkan, dan Anda juga harus meminum banyak air putih.",
			"Bagi Anda orang yang sibuk, mengontrol asupan makanan merupakan hal yang sulit. Biasanya, mereka akan memilih makanan yang cepat disajikan agar tidak memakan waktu mereka terlalu lama. Perlu Anda ketahui bahwa asupan makanan sehat merupakan hal yang sangat penting untuk kesehatan Anda. Dengan memakan makanan sehat, Anda mampu mengendalikan tubuh Anda, kinerja otak Anda akan meningkat, dan juga kesehatan Anda akan terjaga. Inilah beberapa tips makanan sehat yang dapat diterapkan untuk orang orang  sibuk :",
		],
		imageName: "sayur.jpg",
		imageAlt: "sayuran",
	},
	{
		id: 5,
		title: "Pengertian Makanan Sehat dan Contohnya",
		date: "7 September 2021",
		article: [
			"KOMPAS.com – Mengonsumsi makanan sehat mampu membantu mencegah malnutrisi dan berbagai penyakit tidak menular, seperti diabetes, penyakit jantung, stroke, dan kanker.",
			"Sebaliknya, pola makan yang tidak sehat dan kurang aktivitas fisik akan menyebabkan risiko kesehatan yang lebih tinggi.",
			"Dilansir dari World Health Organization (WHO), asupan kalori harus seimbang dengan pengeluarannya agar terhindar dari kenaikan berat badan yang tidak sehat.",
			"Lantas, apa yang dimaksud dengan makanan sehat?",
			"Makanan sehat adalah makanan yang memiliki nutrisi yang beragam dan seimbang yang dibutuhkan oleh tubuh.",
		],
		imageName: "menusehat.jpg",
		imageAlt: "menusehat",
	},
];
